author: Daniel Thorpe
author_url: http://danthorpe.me
github_url: https://github.com/danthorpe/Operations
module: Operations
module_version: 3.1.0
readme: README.md
podspec: Operations.podspec
swift_version: 2.2
sdk: iphoneos
xcodebuild_arguments: -project,Operations.xcodeproj,-scheme,iOS Operations

exclude:
  - Tests

custom_categories:
  - name: Foundations
    children:
    - Operation
    - OperationError
    - OperationQueue
    - OperationQueueDelegate
    - Condition
    - ConditionResult
    - ConditionType
    - ConditionError
    - OperationEvent
    - OperationObserverType        
    - OperationWillExecuteObserver
    - OperationWillCancelObserver    
    - OperationDidCancelObserver
    - OperationDidProduceOperationObserver
    - GroupOperationWillAddChildObserver    
    - OperationWillFinishObserver
    - OperationDidFinishObserver
    - WillExecuteObserver    
    - WillCancelObserver 
    - DidCancelObserver   
    - WillAddChildObserver
    - ProducedOperationObserver     
    - WillFinishObserver
    - DidFinishObserver    
    - OperationObserver    
    - LogSeverity
    - LoggerBlockType
    - LoggerType
    - OperationProfiler
    - ProfileResult
    - Queue

  - name: Building Blocks
    children:
    - GroupOperation
    - BlockOperation
    - AlertOperation
    - ComposedOperation
    - Delay    
    - DelayOperation
    - GatedOperation
    - UIOperation
    - PresentingViewController
    - ViewControllerDisplayStyle
    - ComposedCondition    
    - TrueCondition
    - FalseCondition    
    - MutuallyExclusive
    - NegatedCondition
    - NegatedConditionError
    - SilentCondition
    - NoFailedDependenciesCondition
    - BlockCondition
    - IgnoredCondition
    - BlockObserver
    - BackgroundObserver
    - NetworkObserver
    - TimeoutObserver

  - name: Featured
    children:
    - ReachableOperation
    - WebpageOperation
    - WaitStrategy
    - RepeatedOperation
    - RepeatableOperation
    - RetryOperation
    - ResultOperationType
    - ResultOperation
    - InjectionOperationType
    - AutomaticInjectionOperationType    
    - MapOperation
    - FilterOperation
    - ReachabilityCondition
    - UserNotificationCondition
    - RemoteNotificationCondition
    - TaskOperation
    - URLSessionTaskOperation
    - UserConfirmationCondition

  - name: Location 
    children:
    - LocationManagerType
    - ReverseGeocoderType
    - LocationOperationError
    - UserLocationOperation
    - ReverseGeocodeOperation
    - ReverseGeocodeUserLocationOperation

  - name: Device Capabilities
    children:
    - CapabilityType
    - AuthorizationStatusType
    - CapabilityRegistrarType
    - Capability
    - GetAuthorizationStatus
    - Authorize
    - CapabilityError
    - AuthorizedFor

  - name: Capability.Calendar
    children:
    - Calendar
    - EventsCapabilityRegistrarType
    - EKEventStore
    - EKAuthorizationStatus
    - EventsCapability

  - name: Capability.Cloud
    children:
    - Cloud		
    - CloudContainerRegistrarType
    - CloudStatus
    - CloudCapability
    - CloudContainerRegistrar

  - name: Capability.Health
    children:
    - Health
    - HealthCapabilityStatus
    - HealthRequirement
    - HealthCapabilityRegistrarType
    - HealthCapability

  - name: Capability.Location
    children:
    - Location
    - LocationUsage
    - LocationCapability
    - LocationCapabilityRegistrarType

  - name: Capability.Passbook
    children:
    - Passbook
    - PassbookCapability
    - PassbookCapabilityRegistrarType

  - name: Capability.Photos
    children:
    - Photos
    - PhotosCapability
    - PhotosCapabilityRegistrarType

  - name: CloudKit
    children:
    - CloudKitOperation
    - BatchedCloudKitOperation
    - CloudKitRecovery
    - OPRCKOperation
    - CKOperationType    
    - CKDatabaseOperationType    
    - CKPreviousServerChangeToken    
    - CKMoreComing
    - CKResultsLimit    
    - CKDesiredKeys
    - CKBatchedOperationType    
    - CKDiscoverAllContactsOperationType
    - CKDiscoverUserInfosOperationType
    - CKFetchNotificationChangesOperationType
    - CKFetchRecordChangesOperationType
    - CKFetchRecordZonesOperationType
    - CKFetchRecordsOperationType
    - CKFetchSubscriptionsOperationType
    - CKMarkNotificationsReadOperationType
    - CKModifyBadgeOperationType
    - CKModifyRecordZonesOperationType
    - CKModifyRecordsOperationType
    - CKModifySubscriptionsOperationType
    - CKQueryOperationType

  - name: Address Book
    children:
    - AddressBookPermissionRegistrarError
    - AddressBook
    - AddressBookAddPersonToGroup
    - AddressBookCreateGroup
    - AddressBookDisplayNewPersonViewController
    - AddressBookDisplayPersonViewController
    - AddressBookGetGroup
    - AddressBookGetResource
    - AddressBookGroup
    - AddressBookMapPeople
    - AddressBookOperation
    - AddressBookPerson
    - AddressBookRecord
    - AddressBookRemoveGroup
    - AddressBookRemovePersonFromGroup
    - AddressBookSource
    - AddressBookExternalChangeObserver
    - AddressBookGroupType
    - AddressBookPermissionRegistrar
    - AddressBookPersonType
    - AddressBookRecordType
    - AddressBookSourceType
    - AddressBookType
    - AddressBook_GroupType
    - AddressBook_PersonType
    - AddressBook_SourceType
    - AddressBookCondition
    - AddressBookReadableProperty
    - AddressBookWriteableProperty
    - StorageType
    - MultiValueRepresentable
    - PropertyType
    - ReadablePropertyType
    - WriteablePropertyType
    - LabeledValue
    - SystemAddressBookRegistrar

  - name: Contacts
    children:
    - ContactPredicate
    - ContactsError
    - ContactsPermissionError
    - ContactSaveRequestType
    - ContactStoreType
    - _ContactsCondition
    - _AddContactsToGroup
    - _ContactsAccess
    - _ContactsOperation
    - _GetContacts
    - _GetContactsGroup
    - _RemoveContactsFromGroup
    - _RemoveContactsGroup
    - DisplayContactViewController
    - DisplayCreateContactViewController
    - SystemContactStore

